-- SolarOne relational schema reference.
-- Runtime persistence uses the configured TiDB/MySQL-compatible DATABASE_URL.
-- server/database.ts bootstraps the operational tables used by the current API.
-- This extended reference remains the target model for provider telemetry, auth, and reporting migrations.

CREATE TABLE companies (id UUID PRIMARY KEY, name VARCHAR(160) NOT NULL, slug VARCHAR(120) UNIQUE NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE users (id UUID PRIMARY KEY, company_id UUID REFERENCES companies(id), email VARCHAR(320) UNIQUE NOT NULL, password_hash TEXT NOT NULL, role VARCHAR(32) NOT NULL, email_verified_at TIMESTAMP NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE sites (id UUID PRIMARY KEY, company_id UUID NOT NULL REFERENCES companies(id), customer_id UUID NULL, name VARCHAR(160) NOT NULL, address TEXT, latitude DECIMAL(9,6), longitude DECIMAL(9,6), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE inverter_providers (id UUID PRIMARY KEY, key VARCHAR(80) UNIQUE NOT NULL, display_name VARCHAR(120) NOT NULL, status VARCHAR(32) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE inverter_credentials (id UUID PRIMARY KEY, company_id UUID NOT NULL REFERENCES companies(id), provider_id UUID NOT NULL REFERENCES inverter_providers(id), encrypted_payload TEXT NOT NULL, status VARCHAR(32) NOT NULL, last_error TEXT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE solar_systems (id UUID PRIMARY KEY, site_id UUID NOT NULL REFERENCES sites(id), provider_id UUID REFERENCES inverter_providers(id), credential_id UUID REFERENCES inverter_credentials(id), name VARCHAR(160) NOT NULL, capacity_kw DECIMAL(12,3) NOT NULL, manufacturer VARCHAR(120) NOT NULL, model VARCHAR(160) NOT NULL, serial_number VARCHAR(160), status VARCHAR(32) NOT NULL, last_sync_at TIMESTAMP NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE energy_readings (id UUID PRIMARY KEY, solar_system_id UUID NOT NULL REFERENCES solar_systems(id), timestamp TIMESTAMP NOT NULL, solar_power_kw DECIMAL(12,3), load_power_kw DECIMAL(12,3), grid_import_kw DECIMAL(12,3), grid_export_kw DECIMAL(12,3), battery_soc DECIMAL(5,2), battery_power_kw DECIMAL(12,3), inverter_temperature_c DECIMAL(6,2), inverter_status VARCHAR(32) NOT NULL, fault_code VARCHAR(80), fault_message TEXT, source VARCHAR(32) NOT NULL);
CREATE TABLE alerts (id UUID PRIMARY KEY, company_id UUID NOT NULL REFERENCES companies(id), solar_system_id UUID REFERENCES solar_systems(id), severity VARCHAR(32) NOT NULL, title VARCHAR(160) NOT NULL, message TEXT NOT NULL, acknowledged_at TIMESTAMP NULL, resolved_at TIMESTAMP NULL, occurred_at TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE service_tickets (id UUID PRIMARY KEY, company_id UUID NOT NULL REFERENCES companies(id), solar_system_id UUID REFERENCES solar_systems(id), assigned_user_id UUID REFERENCES users(id), ticket_number VARCHAR(40) UNIQUE NOT NULL, issue TEXT NOT NULL, priority VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE audit_logs (id UUID PRIMARY KEY, company_id UUID REFERENCES companies(id), actor_user_id UUID REFERENCES users(id), action VARCHAR(160) NOT NULL, entity_type VARCHAR(80) NOT NULL, entity_id UUID NULL, metadata_json TEXT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX energy_readings_system_time_idx ON energy_readings(solar_system_id, timestamp);
CREATE INDEX solar_systems_site_status_idx ON solar_systems(site_id, status);
CREATE INDEX alerts_company_severity_idx ON alerts(company_id, severity, occurred_at);

-- Additional operational entities represented in the application domain.
CREATE TABLE customers (id UUID PRIMARY KEY, company_id UUID NOT NULL REFERENCES companies(id), name VARCHAR(160) NOT NULL, email VARCHAR(320), phone VARCHAR(64), address TEXT, notes TEXT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE sites ADD CONSTRAINT sites_customer_fk FOREIGN KEY (customer_id) REFERENCES customers(id);
CREATE TABLE plants (id UUID PRIMARY KEY, site_id UUID NOT NULL REFERENCES sites(id), provider_id UUID REFERENCES inverter_providers(id), external_id VARCHAR(160) NOT NULL, name VARCHAR(160) NOT NULL, capacity_kw DECIMAL(12,3), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE devices (id UUID PRIMARY KEY, plant_id UUID NOT NULL REFERENCES plants(id), external_id VARCHAR(160) NOT NULL, name VARCHAR(160) NOT NULL, manufacturer VARCHAR(120), model VARCHAR(160), serial_number VARCHAR(160), status VARCHAR(32) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE daily_energy (id UUID PRIMARY KEY, solar_system_id UUID NOT NULL REFERENCES solar_systems(id), day DATE NOT NULL, energy_kwh DECIMAL(14,3) NOT NULL, peak_kw DECIMAL(12,3), source VARCHAR(32) NOT NULL, UNIQUE(solar_system_id, day));
CREATE TABLE monthly_energy (id UUID PRIMARY KEY, solar_system_id UUID NOT NULL REFERENCES solar_systems(id), month DATE NOT NULL, energy_kwh DECIMAL(14,3) NOT NULL, peak_kw DECIMAL(12,3), source VARCHAR(32) NOT NULL, UNIQUE(solar_system_id, month));
CREATE TABLE battery_readings (id UUID PRIMARY KEY, solar_system_id UUID NOT NULL REFERENCES solar_systems(id), timestamp TIMESTAMP NOT NULL, soc DECIMAL(5,2), power_kw DECIMAL(12,3), source VARCHAR(32) NOT NULL);
CREATE TABLE grid_readings (id UUID PRIMARY KEY, solar_system_id UUID NOT NULL REFERENCES solar_systems(id), timestamp TIMESTAMP NOT NULL, import_kw DECIMAL(12,3), export_kw DECIMAL(12,3), source VARCHAR(32) NOT NULL);
CREATE TABLE notifications (id UUID PRIMARY KEY, company_id UUID NOT NULL REFERENCES companies(id), user_id UUID REFERENCES users(id), channel VARCHAR(32) NOT NULL, title VARCHAR(160) NOT NULL, body TEXT NOT NULL, status VARCHAR(32) NOT NULL, sent_at TIMESTAMP NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE technicians (id UUID PRIMARY KEY, company_id UUID NOT NULL REFERENCES companies(id), user_id UUID NOT NULL REFERENCES users(id), specialty VARCHAR(120), active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE maintenance_records (id UUID PRIMARY KEY, solar_system_id UUID NOT NULL REFERENCES solar_systems(id), technician_id UUID REFERENCES technicians(id), service_ticket_id UUID REFERENCES service_tickets(id), status VARCHAR(32) NOT NULL, notes TEXT, performed_at TIMESTAMP NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE warranties (id UUID PRIMARY KEY, solar_system_id UUID NOT NULL REFERENCES solar_systems(id), warranty_type VARCHAR(32) NOT NULL, provider_name VARCHAR(160), starts_on DATE, expires_on DATE, status VARCHAR(32) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE reports (id UUID PRIMARY KEY, company_id UUID NOT NULL REFERENCES companies(id), requested_by UUID REFERENCES users(id), report_type VARCHAR(64) NOT NULL, date_from DATE, date_to DATE, status VARCHAR(32) NOT NULL, storage_key TEXT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE subscription_plans (id UUID PRIMARY KEY, key VARCHAR(40) UNIQUE NOT NULL, name VARCHAR(80) NOT NULL, max_systems INTEGER, features_json TEXT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE subscriptions (id UUID PRIMARY KEY, company_id UUID NOT NULL REFERENCES companies(id), plan_id UUID NOT NULL REFERENCES subscription_plans(id), status VARCHAR(32) NOT NULL, starts_at TIMESTAMP NOT NULL, ends_at TIMESTAMP NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE company_settings (company_id UUID PRIMARY KEY REFERENCES companies(id), logo_url TEXT, primary_color VARCHAR(16), secondary_color VARCHAR(16), support_phone VARCHAR(64), support_email VARCHAR(320), custom_domain VARCHAR(255), environmental_factors_json TEXT, notification_settings_json TEXT, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX customers_company_idx ON customers(company_id, created_at);
CREATE INDEX plants_site_idx ON plants(site_id, external_id);
CREATE INDEX devices_plant_idx ON devices(plant_id, external_id);
CREATE INDEX battery_readings_system_time_idx ON battery_readings(solar_system_id, timestamp);
CREATE INDEX grid_readings_system_time_idx ON grid_readings(solar_system_id, timestamp);
CREATE INDEX warranties_expiry_idx ON warranties(expires_on, status);
